# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from referee_msgs/Apriltag_info.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Apriltag_info(genpy.Message):
  _md5sum = "2d3ba812331b080d7cb19d457f299caf"
  _type = "referee_msgs/Apriltag_info"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 tag_num
float32 tag_pos_x
float32 tag_pos_y
float32 tag_pos_z"""
  __slots__ = ['tag_num','tag_pos_x','tag_pos_y','tag_pos_z']
  _slot_types = ['int8','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tag_num,tag_pos_x,tag_pos_y,tag_pos_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Apriltag_info, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.tag_num is None:
        self.tag_num = 0
      if self.tag_pos_x is None:
        self.tag_pos_x = 0.
      if self.tag_pos_y is None:
        self.tag_pos_y = 0.
      if self.tag_pos_z is None:
        self.tag_pos_z = 0.
    else:
      self.tag_num = 0
      self.tag_pos_x = 0.
      self.tag_pos_y = 0.
      self.tag_pos_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_b3f().pack(_x.tag_num, _x.tag_pos_x, _x.tag_pos_y, _x.tag_pos_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.tag_num, _x.tag_pos_x, _x.tag_pos_y, _x.tag_pos_z,) = _get_struct_b3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_b3f().pack(_x.tag_num, _x.tag_pos_x, _x.tag_pos_y, _x.tag_pos_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.tag_num, _x.tag_pos_x, _x.tag_pos_y, _x.tag_pos_z,) = _get_struct_b3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b3f = None
def _get_struct_b3f():
    global _struct_b3f
    if _struct_b3f is None:
        _struct_b3f = struct.Struct("<b3f")
    return _struct_b3f
